#服务器端口
server:
  port: 8107
demo.nacos: ${demo.nacos}
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
blade:
  mybatis-plus:
    sql-log:
      enable: false