
logging:
  level:
    com.yunda.base: debug
spring:
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      async-init: true
      async-close-connection-enable: true
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: return
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
         enabled: true
         url-pattern: /*
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
         session-stat-enable: true
         profile-enable: true
      stat-view-servlet:
         enabled: true
         url-pattern: /druid/*
         login-username: admin
         login-password: admin
         reset-enable: false
         allow:
      filter:
         wall:
           enabled: true
           db-type: mysql
           config:
             alter-table-allow: false
             truncate-allow: false
             drop-table-allow: false
             none-base-statement-allow: false
             update-where-none-check: true
             select-into-outfile-allow: false
             metadata-allow: true
             log-violation: true
             throw-exception: true
         stat:
           log-slow-sql: true
           slow-sql-millis: 1000
           merge-sql: true
           db-type: mysql
           enabled: true
         slf4j:
           enabled: true
           connection-log-enabled: true
           connection-close-after-log-enabled: true
           connection-commit-after-log-enabled: true
           connection-connect-after-log-enabled: true
           connection-connect-before-log-enabled: true
           connection-log-error-enabled: true
           data-source-log-enabled: true
           result-set-log-enabled: true
           statement-log-enabled: true
  custom:
    datasource:
      name: db1,db2,db3,db4
      db1:
        name: db1
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.19.105.135:3306/crmkhnew?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: ydmb
        password: ydmb
      db2:
        name: db2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.19.105.135:3306/crmkhnew?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: ydmb
        password: ydmb
      db3:
        name: db3
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.19.150.148:3306/cainiao?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: ggs
        password: AhIfllYCrPgP4QXM
      db4:
        name: db4
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.19.150.148:3306/pinduoduo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: ggs
        password: AhIfllYCrPgP4QXM
  redis:
      # host: 127.0.0.1
       host: 10.19.106.110
       port: 9400
      # port: 6379
       password:
      # 连接超时时间（毫秒）
       timeout: 10000
       pool:
        # 连接池中的最大空闲连接
        max-idle: 18
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#  rabbitmq:
#      host: 10.19.105.87
#      username: app
#      password: CD6U26RIF6AE
  rabbitmq:
      host: 10.19.160.130
      port: 5672
      username: yunda
      password: yunda
#excel模版下载路径
excel:
  targetFile:
    path: d:/u02/webapps/crmkhnew/resource/
  template:
    path: d:/u02/webapps/crmkhnew/template/
validate:
  url:
    urlNameStringLogin: http://uat.ydauth.yundasys.com:16120/ydauth/actions/outer/user/login.action
    urlNameStringRole: http://uat.ydauth.yundasys.com:16120/ydauth/actions/outer/user/queryUserInfoAndRole.action
    authId: 100000214
taskAbs:
  url:
    ymlTaskCheck: open

